// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​I​'​m​ ​{​n​a​m​e​}​ ​:​)
	 * @param {string} name
	 */
	hi: RequiredParams<'name'>
	/**
	 * W​h​a​t​ ​d​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​k​n​o​w​ ​a​b​o​u​t​ ​m​e​?
	 */
	about: string
}

export type TranslationFunctions = {
	/**
	 * Hi I'm {name} :)
	 */
	hi: (arg: { name: string }) => LocalizedString
	/**
	 * What do you want to know about me?
	 */
	about: () => LocalizedString
}

export type Formatters = {}
