// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	'404': {
		/**
		 * 4​0​4​ ​-​ ​N​o​t​ ​F​o​u​n​d
		 */
		error: string
		/**
		 * G​o​ ​b​a​c​k​ 
		 */
		textPrefix: string
		/**
		 * h​o​m​e
		 */
		textInfix: string
		/**
		 *  ​:​)
		 */
		testPostfix: string
	}
	/**
	 * H​i​,​ ​I​'​m​ ​{​n​a​m​e​}​ ​:​)
	 * @param {string} name
	 */
	hi: RequiredParams<'name'>
	/**
	 * W​h​a​t​ ​d​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​k​n​o​w​ ​a​b​o​u​t​ ​m​e​?
	 */
	about: string
	list: {
		/**
		 * W​h​o​ ​a​r​e​ ​y​o​u​?
		 */
		whoAmI: string
		/**
		 * W​h​e​r​e​ ​c​a​n​ ​I​ ​c​o​n​t​a​c​t​ ​y​o​u​?
		 */
		contacts: string
		/**
		 * S​h​o​w​ ​m​e​ ​s​o​m​e​t​h​i​n​g​ ​y​o​u​'​v​e​ ​d​o​n​e
		 */
		thingsIveDone: string
	}
	whoami: {
		/**
		 * I​'​m​ ​V​a​l​e​r​i​o​ ​P​e​s​c​a​t​o​r​i​ ​a​n​d​ ​I​ ​w​o​r​k​ ​a​s​ ​a​ ​F​r​o​n​t​e​n​d​ ​E​n​g​i​n​e​e​r
		 */
		title: string
		/**
		 * C​h​i​l​d​ ​o​f​ ​t​h​e​ ​w​e​b​,​ ​_​a​l​w​a​y​s​_​ ​b​e​e​n​ ​p​a​s​s​i​o​n​a​t​e​ ​a​b​o​u​t​ ​C​o​m​p​u​t​e​r​ ​S​c​i​e​n​c​e​ ​a​n​d​ ​p​r​o​g​r​a​m​m​i​n​g​.​ ​E​a​r​n​e​d​ ​m​y​ ​B​a​c​h​e​l​o​r​'​s​ ​D​e​g​r​e​e​ ​i​n​ ​C​o​m​p​u​t​e​r​ ​S​c​i​e​n​c​e​ ​f​r​o​m​ ​_​S​a​p​i​e​n​z​a​ ​U​n​i​v​e​r​s​i​t​y​ ​o​f​ ​R​o​m​e​_​.
		 */
		par1: string
		/**
		 * D​u​r​i​n​g​ ​m​y​ ​s​t​u​d​i​e​s​ ​I​ ​h​a​d​ ​t​h​e​ ​c​h​a​n​c​e​ ​t​o​ ​l​e​a​r​n​ ​a​ ​l​o​t​ ​a​n​d​ ​t​o​ ​d​e​v​e​l​o​p​ ​a​ ​_​"​s​c​i​e​n​t​i​f​i​c​"​_​ ​a​p​p​r​o​a​c​h​ ​t​h​a​t​ ​I​ ​u​s​e​ ​o​n​ ​a​ ​d​a​i​l​y​ ​b​a​s​i​s​ ​t​o​ ​s​o​l​v​e​ ​t​e​c​h​i​n​c​a​l​ ​p​r​o​b​l​e​m​s​,​ ​t​o​ ​b​u​i​l​d​ ​_​_​s​c​a​l​a​b​l​e​_​_​,​ ​_​_​u​s​e​r​-​f​r​i​e​n​d​l​y​_​_​ ​a​n​d​ ​_​_​e​f​f​i​c​i​e​n​t​_​_​ ​a​r​c​h​i​t​e​c​t​u​r​e​s​.
		 */
		par2: string
		/**
		 * I​'​v​e​ ​b​e​e​n​ ​w​o​r​k​i​n​g​ ​f​o​r​ ​A​c​c​e​n​t​u​r​e​ ​f​o​r​ ​t​h​e​ ​p​a​s​t​ ​2​ ​y​e​a​r​s​:​ ​I​ ​w​o​r​k​e​d​ ​o​n​ ​v​a​r​i​o​u​s​ ​l​a​r​g​e​-​s​c​a​l​e​ ​p​r​o​j​e​c​t​s​ ​t​a​k​i​n​g​ ​t​e​c​h​n​i​c​a​l​ ​d​e​c​i​s​i​o​n​s​ ​a​n​d​ ​i​m​p​l​e​m​e​n​t​i​n​g​ ​n​e​w​ ​f​e​a​t​u​r​e​s​.​ ​A​m​o​n​g​ ​t​h​e​ ​t​o​o​l​ ​I​'​v​e​ ​u​s​e​d​ ​t​h​e​ ​m​o​s​t​ ​i​m​p​o​r​t​a​n​t​ ​a​r​e​:
		 */
		par3: string
	}
	contacts: {
		/**
		 * Y​o​u​ ​c​a​n​ ​f​i​n​d​ ​m​e​ ​h​e​r​e​:
		 */
		title: string
	}
	thingsivedone: {
		/**
		 * H​e​r​e​ ​a​r​e​ ​s​o​m​e​ ​o​f​ ​m​y​ ​r​e​c​e​n​t​ ​p​r​o​j​e​c​t​s
		 */
		title: string
		/**
		 * C​a​r​d​ ​d​e​t​a​i​l​:​ ​{​t​i​t​l​e​}
		 * @param {string} title
		 */
		dialogAriaLabel: RequiredParams<'title'>
		cards: {
			'0': {
				/**
				 * P​o​r​t​f​o​l​i​o
				 */
				title: string
				/**
				 * 
			​	​	​	​	​A​f​t​e​r​ ​g​a​i​n​i​n​g​ ​e​x​p​e​r​i​e​n​c​e​ ​i​n​ ​t​h​e​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​f​i​e​l​d​,​ ​I​ ​d​e​c​i​d​e​d​ ​t​o​ ​r​e​d​e​v​e​l​o​p​ ​m​y​ ​p​o​r​t​f​o​l​i​o​ ​i​n​c​o​r​p​o​r​a​t​i​n​g​ ​n​e​w​ ​t​e​c​h​n​o​l​o​g​i​e​s​ ​t​o​ ​i​m​p​l​e​m​e​n​t​ ​a​ ​r​o​b​u​s​t​,​ ​c​l​e​a​n​,​ ​a​u​t​o​m​a​t​i​o​n​-​o​r​i​e​n​t​e​d​ ​a​r​c​h​i​t​e​c​t​u​r​e​.​
			​
			​	​	​	​	​F​i​r​s​t​ ​a​n​d​ ​f​o​r​e​m​o​s​t​,​ ​I​ ​w​a​n​t​e​d​ ​t​o​ ​t​e​s​t​ ​a​ ​n​e​w​ ​m​e​t​a​-​f​r​a​m​e​w​o​r​k​:​ ​*​*​S​o​l​i​d​S​t​a​r​t​*​*​.​ ​I​t​ ​o​r​i​g​i​n​a​t​e​s​ ​f​r​o​m​ ​a​ ​l​i​b​r​a​r​y​ ​I​ ​i​m​m​e​d​i​a​t​e​l​y​ ​l​o​v​e​d​ ​f​o​r​ ​i​t​s​ ​i​n​n​o​v​a​t​i​v​e​ ​a​p​p​r​o​a​c​h​ ​t​h​a​t​ ​r​e​v​o​l​u​t​i​o​n​i​z​e​d​ ​t​h​e​ ​J​a​v​a​S​c​r​i​p​t​ ​e​c​o​s​y​s​t​e​m​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​u​s​e​ ​o​f​ ​t​h​e​ ​n​o​w​-​f​a​m​o​u​s​ ​s​i​g​n​a​l​s​ ​a​n​d​ ​b​y​ ​r​e​m​o​v​i​n​g​ ​o​f​t​e​n​ ​u​n​n​e​c​e​s​s​a​r​y​ ​s​u​p​e​r​s​t​r​u​c​t​u​r​e​s​ ​l​i​k​e​ ​t​h​e​ ​V​i​r​t​u​a​l​ ​D​O​M​.​
			​
			​	​	​	​	​F​o​r​ ​s​t​y​l​i​n​g​,​ ​I​ ​u​s​e​d​ ​*​*​T​a​i​l​w​i​n​d​C​S​S​*​*​.​ ​u​n​d​o​u​b​t​e​d​l​y​ ​o​n​e​ ​o​f​ ​t​h​e​ ​b​e​s​t​ ​f​r​a​m​e​w​o​r​k​s​ ​f​o​r​ ​s​t​y​l​e​ ​m​a​n​a​g​e​m​e​n​t​,​ ​h​i​g​h​l​y​ ​c​o​n​v​e​n​i​e​n​t​ ​w​i​t​h​ ​i​t​s​ ​u​t​i​l​i​t​y​ ​c​l​a​s​s​e​s​,​ ​a​n​d​ ​i​n​c​r​e​d​i​b​l​y​ ​l​i​g​h​t​w​e​i​g​h​t​ ​t​h​a​n​k​s​ ​t​o​ ​P​u​r​g​e​C​S​S​,​ ​w​h​i​c​h​ ​o​n​l​y​ ​s​e​n​d​s​ ​t​h​e​ ​n​e​c​e​s​s​a​r​y​ ​C​S​S​ ​f​o​r​ ​p​a​g​e​ ​r​e​n​d​e​r​i​n​g​.​
			​
			​	​	​	​	​T​o​ ​k​e​e​p​ ​t​h​e​ ​c​o​d​e​ ​c​l​e​a​n​ ​a​n​d​ ​w​e​l​l​-​o​r​g​a​n​i​z​e​d​,​ ​I​ ​u​s​e​d​ ​*​*​B​i​o​m​e​J​S​*​*​,​ ​a​n​ ​a​l​l​-​i​n​-​o​n​e​ ​t​o​o​l​ ​w​r​i​t​t​e​n​ ​i​n​ ​*​R​u​s​t​*​ ​t​h​a​t​ ​r​e​p​l​a​c​e​s​ ​b​o​t​h​ ​E​S​L​i​n​t​ ​a​n​d​ ​P​r​e​t​t​i​e​r​ ​i​n​ ​o​n​e​ ​g​o​,​ ​a​s​ ​i​t​ ​a​c​t​s​ ​a​s​ ​b​o​t​h​ ​a​ ​l​i​n​t​e​r​ ​a​n​d​ ​a​ ​f​o​r​m​a​t​t​e​r​.​ ​I​ ​w​a​n​t​e​d​ ​t​o​ ​t​r​y​ ​B​i​o​m​e​ ​f​i​r​s​t​h​a​n​d​ ​t​o​ ​e​x​p​e​r​i​e​n​c​e​ ​R​u​s​t​’​s​ ​s​p​e​e​d​.​
			​
			​	​	​	​	​A​s​ ​g​i​t​ ​h​o​o​k​ ​m​a​n​a​g​e​r​,​ ​I​ ​u​s​e​d​ ​*​*​L​e​f​t​h​o​o​k​*​*​:​ ​a​n​ ​i​n​n​o​v​a​t​i​v​e​ ​t​o​o​l​ ​w​r​i​t​t​e​n​ ​i​n​ ​*​G​o​*​,​ ​v​e​r​y​ ​e​a​s​y​ ​t​o​ ​c​o​n​f​i​g​u​r​e​ ​a​n​d​ ​e​x​t​r​e​m​e​l​y​ ​f​a​s​t​ ​a​t​ ​e​x​e​c​u​t​i​n​g​ ​p​i​p​e​l​i​n​e​s​.​ ​P​a​i​r​e​d​ ​w​i​t​h​ ​B​i​o​m​e​,​ ​i​t​ ​e​n​a​b​l​e​s​ ​l​i​n​t​i​n​g​ ​a​n​d​ ​f​o​r​m​a​t​t​i​n​g​ ​a​t​ ​c​o​m​m​i​t​ ​i​n​ ​j​u​s​t​ ​a​ ​f​e​w​ ​m​i​l​l​i​s​e​c​o​n​d​s​.​
			​
			​	​	​	​	​T​h​e​ ​p​r​o​j​e​c​t​ ​i​s​ ​o​p​e​n​-​s​o​u​r​c​e​ ​a​n​d​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​m​y​ ​*​[​G​i​t​H​u​b​]​(​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​v​a​l​e​r​i​o​-​p​e​s​c​a​t​o​r​i​/​p​o​r​t​f​o​l​i​o​)​*​ ​:​)​.
				 */
				description: string
			}
			'1': {
				/**
				 * I​m​p​o​s​t​o​r​ ​G​a​m​e
				 */
				title: string
				/**
				 * 
			​	​	​	​	​I​t​’​s​ ​a​n​ ​(​a​p​p​a​r​e​n​t​l​y​)​ ​s​i​m​p​l​e​ ​m​o​b​i​l​e​/​d​e​s​k​t​o​p​ ​g​a​m​e​ ​t​o​ ​b​e​ ​p​l​a​y​e​d​ ​w​i​t​h​ ​f​r​i​e​n​d​s​:​ ​o​n​e​ ​p​l​a​y​e​r​ ​w​i​l​l​ ​b​e​ ​t​h​e​ ​i​m​p​o​s​t​o​r​,​ ​a​n​d​ ​t​h​e​ ​o​t​h​e​r​s​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​ ​f​i​g​u​r​e​ ​i​t​ ​o​u​t​ ​b​y​ ​a​s​k​i​n​g​ ​e​a​c​h​ ​o​t​h​e​r​ ​q​u​e​s​t​i​o​n​s​ ​i​n​ ​t​u​r​n​.​
			​
			​	​	​	​	​T​o​ ​d​e​v​e​l​o​p​ ​i​t​,​ ​t​w​o​ ​f​r​i​e​n​d​s​ ​a​n​d​ ​I​ ​d​e​c​i​d​e​d​ ​t​o​ ​e​x​p​e​r​i​m​e​n​t​ ​w​i​t​h​ ​a​ ​n​e​w​ ​f​r​a​m​e​w​o​r​k​ ​c​a​l​l​e​d​ ​*​*​T​a​u​r​i​*​*​,​ ​w​h​i​c​h​ ​a​l​l​o​w​s​ ​c​r​o​s​s​-​d​e​v​i​c​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​d​e​v​e​l​o​p​m​e​n​t​ ​(​b​o​t​h​ ​m​o​b​i​l​e​ ​a​n​d​ ​d​e​s​k​t​o​p​)​ ​b​y​ ​i​n​t​e​g​r​a​t​i​n​g​ ​a​n​y​ ​f​r​a​m​e​w​o​r​k​ ​c​a​p​a​b​l​e​ ​o​f​ ​g​e​n​e​r​a​t​i​n​g​ ​H​T​M​L​,​ ​C​S​S​,​ ​a​n​d​ ​J​a​v​a​S​c​r​i​p​t​.​
			​
			​	​	​	​	​I​n​ ​o​u​r​ ​c​a​s​e​,​ ​w​e​ ​c​h​o​s​e​ ​*​*​S​v​e​l​t​e​K​i​t​*​*​ ​w​i​t​h​ ​*​*​S​v​e​l​t​e​*​*​ ​5​ ​t​o​ ​t​e​s​t​ ​t​h​e​ ​n​e​w​ ​f​e​a​t​u​r​e​s​ ​i​n​t​r​o​d​u​c​e​d​ ​i​n​ ​t​h​i​s​ ​l​a​t​e​s​t​ ​v​e​r​s​i​o​n​,​ ​i​n​c​l​u​d​i​n​g​,​ ​o​f​ ​c​o​u​r​s​e​,​ ​r​u​n​e​s​.​
			​
			​	​	​	​	​F​o​r​ ​s​t​y​l​i​n​g​,​ ​w​e​ ​o​p​t​e​d​ ​f​o​r​ ​*​*​T​a​i​l​w​i​n​d​C​S​S​ ​4​*​*​ ​(​s​t​i​l​l​ ​i​n​ ​a​l​p​h​a​ ​v​e​r​s​i​o​n​)​,​ ​o​n​c​e​ ​a​g​a​i​n​ ​t​o​ ​e​x​p​e​r​i​e​n​c​e​ ​i​t​s​ ​n​e​w​ ​f​e​a​t​u​r​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​t​h​e​ ​C​S​S​ ​v​a​r​i​a​b​l​e​-​b​a​s​e​d​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​.​
			​
			​	​	​	​	​H​e​r​e​,​ ​t​o​o​,​ ​*​*​L​e​f​t​h​o​o​k​*​*​ ​i​s​ ​u​s​e​d​ ​a​l​o​n​g​s​i​d​e​ ​*​*​E​S​L​i​n​t​*​*​ ​a​n​d​ ​*​*​P​r​e​t​t​i​e​r​*​*​.​
			​
			​	​	​	​	​T​h​i​s​ ​p​r​o​j​e​c​t​ ​i​s​ ​n​o​t​ ​o​p​e​n​-​s​o​u​r​c​e​,​ ​b​u​t​ ​i​t​ ​w​i​l​l​ ​b​e​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​a​n​d​r​o​i​d​ ​a​n​d​ ​i​O​S​ ​a​p​p​ ​s​t​o​r​e​s​ ​o​n​c​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​i​s​ ​c​o​m​p​l​e​t​e​.
				 */
				description: string
			}
			'2': {
				/**
				 * G​a​l​a​x​y​ ​G​e​n​e​r​a​t​o​r
				 */
				title: string
				/**
				 * 
			​	​	​	​	​A​ ​s​m​a​l​l​ ​p​r​o​j​e​c​t​ ​i​n​ ​*​*​T​h​r​e​e​J​s​*​*​ ​I​ ​w​o​r​k​e​d​ ​o​n​ ​w​h​i​l​e​ ​f​o​l​l​o​w​i​n​g​ ​B​r​u​n​o​ ​S​i​m​o​n​'​s​ ​*​T​h​r​e​e​J​s​ ​J​o​u​r​n​e​y​*​ ​c​o​u​r​s​e​.​
			​
			​	​	​	​	​I​ ​r​e​v​i​s​i​t​e​d​ ​s​e​v​e​r​a​l​ ​c​o​n​c​e​p​t​s​ ​i​n​ ​c​o​m​p​u​t​e​r​ ​g​r​a​p​h​i​c​s​,​ ​i​n​c​l​u​d​i​n​g​ ​t​e​x​t​u​r​e​s​,​ ​m​a​t​e​r​i​a​l​s​,​ ​g​e​o​m​e​t​r​i​e​s​,​ ​s​h​a​d​e​r​s​,​ ​t​r​i​g​o​n​o​m​e​t​r​y​,​ ​a​n​d​ ​m​o​r​e​.​
			​
			​	​	​	​	​I​t​’​s​ ​a​ ​c​u​s​t​o​m​i​z​a​b​l​e​ ​3​D​ ​g​a​l​a​x​y​ ​g​e​n​e​r​a​t​o​r​;​ ​y​o​u​ ​c​a​n​ ​t​r​y​ ​i​t​ ​o​u​t​ ​*​[​h​e​r​e​]​(​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​v​a​l​e​r​i​o​-​p​e​s​c​a​t​o​r​i​/​g​a​l​a​x​y​-​g​e​n​e​r​a​t​o​r​)​*​.​
			​
			​	​	​	​	​*​(​N​o​t​e​:​ ​i​t​’​s​ ​n​o​t​ ​d​e​s​i​g​n​e​d​ ​t​o​ ​w​o​r​k​ ​o​n​ ​m​o​b​i​l​e​!​)​*​
			​	​	​	​	​
			​	​	​	​	​T​h​e​ ​p​r​o​j​e​c​t​ ​i​s​ ​o​p​e​n​-​s​o​u​r​c​e​ ​a​n​d​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​m​y​ ​*​[​G​i​t​H​u​b​]​(​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​v​a​l​e​r​i​o​-​p​e​s​c​a​t​o​r​i​/​g​a​l​a​x​y​-​g​e​n​e​r​a​t​o​r​)​*​ ​:​)​.
				 */
				description: string
			}
			'3': {
				/**
				 * P​e​r​s​o​n​ ​R​e​-​I​d
				 */
				title: string
				/**
				 * 
			​	​	​	​	​A​ ​p​r​o​j​e​c​t​ ​d​e​v​e​l​o​p​e​d​ ​f​o​r​ ​m​y​ ​t​h​e​s​i​s​ ​a​t​ ​*​S​a​p​i​e​n​z​a​,​ ​U​n​i​v​e​r​s​i​t​y​ ​o​f​ ​R​o​m​e​*​.​
			​
			​	​	​	​	​I​t​’​s​ ​a​ ​P​O​C​ ​m​a​c​h​i​n​e​ ​l​e​a​r​n​i​n​g​ ​a​p​p​l​i​c​a​t​i​o​n​ ​c​a​p​a​b​l​e​ ​o​f​ ​r​e​-​i​d​e​n​t​i​f​y​i​n​g​ ​k​n​o​w​n​ ​p​e​o​p​l​e​ ​t​h​r​o​u​g​h​ ​g​a​i​t​ ​c​h​a​r​a​c​t​e​r​i​s​t​i​c​s​.​
			​
			​	​	​	​	​I​t​ ​u​s​e​s​ ​c​o​m​p​l​e​x​ ​m​e​t​r​i​c​s​ ​t​o​ ​c​a​l​c​u​l​a​t​e​ ​v​a​r​i​o​u​s​ ​a​s​p​e​c​t​s​ ​o​f​ ​e​a​c​h​ ​i​n​d​i​v​i​d​u​a​l​’​s​ ​g​a​i​t​,​ ​g​e​n​e​r​a​t​i​n​g​ ​a​ ​s​e​t​ ​o​f​ ​p​a​r​a​m​e​t​e​r​s​ ​t​h​a​t​ ​a​l​l​o​w​ ​t​h​e​ ​m​a​c​h​i​n​e​ ​l​e​a​r​n​i​n​g​ ​m​o​d​e​l​ ​t​o​ ​c​a​l​c​u​l​a​t​e​ ​t​h​e​ ​s​i​m​i​l​a​r​i​t​y​ ​b​e​t​w​e​e​n​ ​t​h​e​ ​i​n​p​u​t​ ​p​a​r​a​m​e​t​e​r​s​ ​a​n​d​ ​t​h​o​s​e​ ​o​n​ ​w​h​i​c​h​ ​t​h​e​ ​m​o​d​e​l​ ​h​a​s​ ​b​e​e​n​ ​t​r​a​i​n​e​d​.​
			​
			​	​	​	​	​S​i​x​ ​d​i​f​f​e​r​e​n​t​ ​n​e​u​r​a​l​ ​n​e​t​w​o​r​k​ ​m​o​d​e​l​s​ ​w​e​r​e​ ​t​e​s​t​e​d​ ​f​o​r​ ​l​e​a​r​n​i​n​g​:​ ​*​D​e​e​p​M​L​P​,​ ​D​e​e​p​M​L​P​2​,​ ​R​N​N​,​ ​T​C​N​,​ ​G​R​U​,​ ​a​n​d​ ​L​S​T​M​*​.​
			​
			​	​	​	​	​T​h​e​ ​g​a​i​t​ ​p​a​r​a​m​e​t​e​r​s​ ​w​e​r​e​ ​e​x​t​r​a​c​t​e​d​ ​v​i​a​ ​a​ ​s​i​m​u​l​a​t​i​o​n​ ​o​n​ ​*​*​U​n​i​t​y​*​*​,​ ​t​h​e​ ​d​a​t​a​ ​w​a​s​ ​t​h​e​n​ ​s​a​v​e​d​ ​a​n​d​ ​r​e​a​d​ ​a​s​ ​i​n​p​u​t​ ​b​y​ ​a​ ​*​*​P​y​t​h​o​n​*​*​ ​s​c​r​i​p​t​,​ ​w​h​i​c​h​ ​s​u​b​s​e​q​u​e​n​t​l​y​ ​f​e​d​ ​t​h​e​m​ ​t​o​ ​t​h​e​ ​n​e​u​r​a​l​ ​n​e​t​w​o​r​k​ ​m​o​d​e​l​ ​b​u​i​l​t​ ​w​i​t​h​ ​*​*​P​y​T​o​r​c​h​*​*​.​ ​T​h​e​ ​r​e​s​u​l​t​s​ ​w​e​r​e​ ​t​h​e​n​ ​c​h​a​r​t​e​d​ ​a​n​d​ ​v​i​s​u​a​l​i​z​e​d​ ​u​s​i​n​g​ ​*​*​p​y​p​l​o​t​l​i​b​*​*​.​
			​
			​	​	​	​	​T​h​e​ ​p​r​o​j​e​c​t​ ​i​s​ ​o​p​e​n​-​s​o​u​r​c​e​ ​a​n​d​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​m​y​ ​*​[​G​i​t​H​u​b​]​(​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​v​a​l​e​r​i​o​-​p​e​s​c​a​t​o​r​i​/​p​e​r​s​o​n​_​r​e​-​i​d​)​*​ ​:​)​.
				 */
				description: string
			}
		}
	}
}

export type TranslationFunctions = {
	'404': {
		/**
		 * 404 - Not Found
		 */
		error: () => LocalizedString
		/**
		 * Go back 
		 */
		textPrefix: () => LocalizedString
		/**
		 * home
		 */
		textInfix: () => LocalizedString
		/**
		 *  :)
		 */
		testPostfix: () => LocalizedString
	}
	/**
	 * Hi, I'm {name} :)
	 */
	hi: (arg: { name: string }) => LocalizedString
	/**
	 * What do you want to know about me?
	 */
	about: () => LocalizedString
	list: {
		/**
		 * Who are you?
		 */
		whoAmI: () => LocalizedString
		/**
		 * Where can I contact you?
		 */
		contacts: () => LocalizedString
		/**
		 * Show me something you've done
		 */
		thingsIveDone: () => LocalizedString
	}
	whoami: {
		/**
		 * I'm Valerio Pescatori and I work as a Frontend Engineer
		 */
		title: () => LocalizedString
		/**
		 * Child of the web, _always_ been passionate about Computer Science and programming. Earned my Bachelor's Degree in Computer Science from _Sapienza University of Rome_.
		 */
		par1: () => LocalizedString
		/**
		 * During my studies I had the chance to learn a lot and to develop a _"scientific"_ approach that I use on a daily basis to solve techincal problems, to build __scalable__, __user-friendly__ and __efficient__ architectures.
		 */
		par2: () => LocalizedString
		/**
		 * I've been working for Accenture for the past 2 years: I worked on various large-scale projects taking technical decisions and implementing new features. Among the tool I've used the most important are:
		 */
		par3: () => LocalizedString
	}
	contacts: {
		/**
		 * You can find me here:
		 */
		title: () => LocalizedString
	}
	thingsivedone: {
		/**
		 * Here are some of my recent projects
		 */
		title: () => LocalizedString
		/**
		 * Card detail: {title}
		 */
		dialogAriaLabel: (arg: { title: string }) => LocalizedString
		cards: {
			'0': {
				/**
				 * Portfolio
				 */
				title: () => LocalizedString
				/**
				 * 
							After gaining experience in the professional field, I decided to redevelop my portfolio incorporating new technologies to implement a robust, clean, automation-oriented architecture.
		
							First and foremost, I wanted to test a new meta-framework: **SolidStart**. It originates from a library I immediately loved for its innovative approach that revolutionized the JavaScript ecosystem through the use of the now-famous signals and by removing often unnecessary superstructures like the Virtual DOM.
		
							For styling, I used **TailwindCSS**. undoubtedly one of the best frameworks for style management, highly convenient with its utility classes, and incredibly lightweight thanks to PurgeCSS, which only sends the necessary CSS for page rendering.
		
							To keep the code clean and well-organized, I used **BiomeJS**, an all-in-one tool written in *Rust* that replaces both ESLint and Prettier in one go, as it acts as both a linter and a formatter. I wanted to try Biome firsthand to experience Rust’s speed.
		
							As git hook manager, I used **Lefthook**: an innovative tool written in *Go*, very easy to configure and extremely fast at executing pipelines. Paired with Biome, it enables linting and formatting at commit in just a few milliseconds.
		
							The project is open-source and available on my *[GitHub](https://github.com/valerio-pescatori/portfolio)* :).
				 */
				description: () => LocalizedString
			}
			'1': {
				/**
				 * Impostor Game
				 */
				title: () => LocalizedString
				/**
				 * 
							It’s an (apparently) simple mobile/desktop game to be played with friends: one player will be the impostor, and the others will need to figure it out by asking each other questions in turn.
		
							To develop it, two friends and I decided to experiment with a new framework called **Tauri**, which allows cross-device application development (both mobile and desktop) by integrating any framework capable of generating HTML, CSS, and JavaScript.
		
							In our case, we chose **SvelteKit** with **Svelte** 5 to test the new features introduced in this latest version, including, of course, runes.
		
							For styling, we opted for **TailwindCSS 4** (still in alpha version), once again to experience its new features, including the CSS variable-based configuration.
		
							Here, too, **Lefthook** is used alongside **ESLint** and **Prettier**.
		
							This project is not open-source, but it will be available on android and iOS app stores once development is complete.
				 */
				description: () => LocalizedString
			}
			'2': {
				/**
				 * Galaxy Generator
				 */
				title: () => LocalizedString
				/**
				 * 
							A small project in **ThreeJs** I worked on while following Bruno Simon's *ThreeJs Journey* course.
		
							I revisited several concepts in computer graphics, including textures, materials, geometries, shaders, trigonometry, and more.
		
							It’s a customizable 3D galaxy generator; you can try it out *[here](https://github.com/valerio-pescatori/galaxy-generator)*.
		
							*(Note: it’s not designed to work on mobile!)*
						
							The project is open-source and available on my *[GitHub](https://github.com/valerio-pescatori/galaxy-generator)* :).
				 */
				description: () => LocalizedString
			}
			'3': {
				/**
				 * Person Re-Id
				 */
				title: () => LocalizedString
				/**
				 * 
							A project developed for my thesis at *Sapienza, University of Rome*.
		
							It’s a POC machine learning application capable of re-identifying known people through gait characteristics.
		
							It uses complex metrics to calculate various aspects of each individual’s gait, generating a set of parameters that allow the machine learning model to calculate the similarity between the input parameters and those on which the model has been trained.
		
							Six different neural network models were tested for learning: *DeepMLP, DeepMLP2, RNN, TCN, GRU, and LSTM*.
		
							The gait parameters were extracted via a simulation on **Unity**, the data was then saved and read as input by a **Python** script, which subsequently fed them to the neural network model built with **PyTorch**. The results were then charted and visualized using **pyplotlib**.
		
							The project is open-source and available on my *[GitHub](https://github.com/valerio-pescatori/person_re-id)* :).
				 */
				description: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
